### ISSUE TITLE
Code bug in xStream 1.4.8 (java.lang.NoSuchFieldError: serializationMembers)?

### ISSUE THREAD

**Issue by vvishnoi** [maurotalevi/xstream#1]
I am upgrading xStream 1.2 to xStream 1.4.8

I get the following error on application startup:

Caused by: java.lang.NoSuchFieldError: serializationMembers
                at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.<init>(AbstractReflectionConverter.java:62)
                at com.thoughtworks.xstream.converters.reflection.ReflectionConverter.<init>(reflection:ReflectionConverter.java):8)
                at com.thoughtworks.xstream.annotations.AnnotationReflectionConverter.<init>(AnnotationReflectionConverter.java:49)
                ... 37 more

It seems a code bug (in version 1.4.8) to me: AbstractReflectionConverter class accesses serializationMembers field member of serializationMethodInvoker class, serializationMembers is moved to util package in 1.4.8 but access modifier is still default. Which could be an issue because AbstractReflectionConverter and SerializationMethodInvoker both are in the same package but SerializationMembers is in a different package, so access modifier should be changed to public or it should be accessed using getter methods. 

AbstractReflectionConverter.Java:    
   Line 62:  serializationMembers = serializationMethodInvoker.serializationMembers;

SerializationMethodInvoker.Java
Line 30:   SerializationMembers serializationMembers = new SerializationMembers();

As per documentation this class has been moved to util package. nt

Please let me know if my understanding is correct or doing anything wrong here.

**Comment by vvishnoi** [comment]
Not an issue, I had an old version in the classpath. 
-verbose:class command line option helped to find out which class is loaded from where.
Sorry for the confusion.
